vim.print("All modules and specs are ready...😊")
require("core.nvim-options.keymaps")
require("core.nvim-options.keys.helpers")
require("core.nvim-options.icons")
require("core.nvim-options.usrsettings")
require("core.utils.autocmds")
require("core.utils.abbr")
require("core.nvim-options.LspSettings.lua_ls")
require("core.nvim-options.LspSettings.json_ls")
require("lazy_build")
--
spec("plugins")

-- LSP :Plugins
spec("plugins.lsp.lspconfig")
spec("plugins.lsp.lua-snip")
spec("plugins.lsp.mason")
spec("plugins.lsp.nvim-lightbulb")
spec("plugins.lsp.lspconfig")
spec("plugins.lsp.lsp-format")
spec("plugins.lsp.indent-blankline")
-- spec("plugins.lsp.nvim-cmp")
spec("plugins.lsp.mini_cmp")
--UI : PLugins
spec("plugins.ui.toggle-term")
spec("plugins.ui.whichkey")
spec("plugins.ui.nui")
spec("plugins.ui.lua-line")
spec("plugins.ui.colorizer")
spec("plugins.ui.dressing")
spec("plugins.ui.onedark")
spec("plugins.ui.molten")
spec("plugins.other")
spec("plugins.telescope")
